# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c14e2530ca3506683d3e532fd26b93b2886ea7876b20be57825041fb139caa724fa025b88fe68f8b83e2989a76c79bea25063a341271a930bfefa9b8f822b7be

test:
  secret_key_base: 4dc3464a9ea0aa5c6429038eb88cbae6ef0c3f5d2dc94c596da6628025ae5b70bebeedd0c9bac52caa6fffa980636680b03d8f116a7f78bf1efa225cdf7c3087

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
